version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: HussainCS211210
      MYSQL_DATABASE: school_management
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  school-app:
    build: .
    container_name: school-app-container
    restart: always
    ports:
      - "9999:9999"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/school_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: HussainCS 211210

volumes:
  mysql-data:
